#!/bin/bash
pacup -s packages/os-installer-git/os-installer-git.pacscript
pacup -s packages/pacget-git/pacget-git.pacscript
pacup -s packages/paconvert-git/paconvert-git.pacscript
pacup -s packages/pacstall-gui-git/pacstall-gui-git.pacscript
pacup -s packages/pacup-bin/pacup-bin.pacscript
pacup -s packages/panagement/panagement.pacscript
pacup -s packages/paper-icon-theme/paper-icon-theme.pacscript
pacup -s packages/papirus-icon-theme/papirus-icon-theme.pacscript
pacup -s packages/pap/pap.pacscript
pacup -s packages/parsec-deb/parsec-deb.pacscript
pacup -s packages/pdf-mix-tool-git/pdf-mix-tool-git.pacscript
pacup -s packages/pdfmm-git/pdfmm-git.pacscript
pacup -s packages/pfetch-bin/pfetch-bin.pacscript
pacup -s packages/pgmigrate/pgmigrate.pacscript
pacup -s packages/pipes.sh-bin/pipes.sh-bin.pacscript
pacup -s packages/pipewire/pipewire.pacscript
pacup -s packages/planner-git/planner-git.pacscript
pacup -s packages/plexmediaserver-deb/plexmediaserver-deb.pacscript
pacup -s packages/polybar/polybar.pacscript
pacup -s packages/pomatez-deb/pomatez-deb.pacscript
pacup -s packages/popcorn-time-deb/popcorn-time-deb.pacscript
pacup -s packages/popsicle/popsicle.pacscript
pacup -s packages/postman-bin/postman-bin.pacscript
pacup -s packages/powertop-git/powertop-git.pacscript
pacup -s packages/prismlauncher-git/prismlauncher-git.pacscript
pacup -s packages/protonmail-bridge-deb/protonmail-bridge-deb.pacscript
pacup -s packages/proton-python-client/proton-python-client.pacscript
pacup -s packages/protonup-qt-app/protonup-qt-app.pacscript
pacup -s packages/protonvpn-cli/protonvpn-cli.pacscript
pacup -s packages/protonvpn-gui/protonvpn-gui.pacscript
pacup -s packages/protonvpn-nm-lib/protonvpn-nm-lib.pacscript
pacup -s packages/pulsar-deb/pulsar-deb.pacscript
pacup -s packages/pycharm-community-bin/pycharm-community-bin.pacscript
pacup -s packages/python3-imdbpy-deb/python3-imdbpy-deb.pacscript
pacup -s packages/qogir-gtk-theme-bin/qogir-gtk-theme-bin.pacscript
pacup -s packages/qogir-icon-theme-bin/qogir-icon-theme-bin.pacscript
pacup -s packages/qtile-extras-git/qtile-extras-git.pacscript
pacup -s packages/qtile-git/qtile-git.pacscript
pacup -s packages/quarto-deb/quarto-deb.pacscript
pacup -s packages/quintom-cursor-theme-git/quintom-cursor-theme-git.pacscript
pacup -s packages/realvnc-vnc-viewer-deb/realvnc-vnc-viewer-deb.pacscript
pacup -s packages/renegate/renegate.pacscript
pacup -s packages/reshade-shaders-git/reshade-shaders-git.pacscript
pacup -s packages/rhino-core/rhino-core.pacscript
pacup -s packages/rhino-kvantum-theme-git/rhino-kvantum-theme-git.pacscript
pacup -s packages/rhino-lightdm-theme-git/rhino-lightdm-theme-git.pacscript
pacup -s packages/rhino-linux-xfce4-config-git/rhino-linux-xfce4-config-git.pacscript
pacup -s packages/rhino-neofetch-git/rhino-neofetch-git.pacscript
pacup -s packages/rhino-pine-core/rhino-pine-core.pacscript
pacup -s packages/rhino-pkg-git/rhino-pkg-git.pacscript
pacup -s packages/rhino-plymouth-theme-git/rhino-plymouth-theme-git.pacscript
pacup -s packages/rhino-server-core/rhino-server-core.pacscript
pacup -s packages/rhino-setup-bin/rhino-setup-bin.pacscript
pacup -s packages/rhino-setup-git/rhino-setup-git.pacscript
pacup -s packages/rhino-xfce4-mobile-config-git/rhino-xfce4-mobile-config-git.pacscript
pacup -s packages/rstudio-deb/rstudio-deb.pacscript
pacup -s packages/sed/sed.pacscript
pacup -s packages/shellcheck-bin/shellcheck-bin.pacscript
pacup -s packages/shell-color-scripts/shell-color-scripts.pacscript
pacup -s packages/shellharden/shellharden.pacscript
pacup -s packages/shfmt-bin/shfmt-bin.pacscript
pacup -s packages/signal-desktop-beta-deb/signal-desktop-beta-deb.pacscript
pacup -s packages/signal-desktop-deb/signal-desktop-deb.pacscript
pacup -s packages/slack-deb/slack-deb.pacscript
pacup -s packages/slop-git/slop-git.pacscript
pacup -s packages/smartgit/smartgit.pacscript
pacup -s packages/smplayer-deb/smplayer-deb.pacscript
pacup -s packages/songrec-deb/songrec-deb.pacscript
pacup -s packages/soundux/soundux.pacscript
pacup -s packages/spacecadetpinball-git/spacecadetpinball-git.pacscript
pacup -s packages/spot-client-git/spot-client-git.pacscript
pacup -s packages/spotify-client-deb/spotify-client-deb.pacscript
pacup -s packages/starship-bin/starship-bin.pacscript
pacup -s packages/st-distrotube-git/st-distrotube-git.pacscript
pacup -s packages/steam-deb/steam-deb.pacscript
pacup -s packages/steam-launcher-deb/steam-launcher-deb.pacscript
pacup -s packages/steamtinkerlaunch-git/steamtinkerlaunch-git.pacscript
pacup -s packages/stellarium/stellarium.pacscript
pacup -s packages/st-lukesmith-git/st-lukesmith-git.pacscript
pacup -s packages/sublime-merge-deb/sublime-merge-deb.pacscript
pacup -s packages/sublime-text-deb/sublime-text-deb.pacscript
pacup -s packages/surf-distrotube-git/surf-distrotube-git.pacscript
pacup -s packages/surfshark-gui-deb/surfshark-gui-deb.pacscript
pacup -s packages/surf/surf.pacscript
pacup -s packages/suru-icon-theme-git/suru-icon-theme-git.pacscript
pacup -s packages/systemcoding-conky/systemcoding-conky.pacscript
pacup -s packages/tabby-deb/tabby-deb.pacscript
pacup -s packages/taskwarrior/taskwarrior.pacscript
pacup -s packages/teams-for-linux-deb/teams-for-linux-deb.pacscript
pacup -s packages/teamviewer-deb/teamviewer-deb.pacscript
pacup -s packages/telegram-bin/telegram-bin.pacscript
pacup -s packages/tenacity-git/tenacity-git.pacscript
pacup -s packages/thorium-deb/thorium-deb.pacscript
pacup -s packages/thrive-deb/thrive-deb.pacscript
pacup -s packages/tidal-hifi-bin/tidal-hifi-bin.pacscript
pacup -s packages/timeshift/timeshift.pacscript
pacup -s packages/tixati-deb/tixati-deb.pacscript
pacup -s packages/tmpmail-bin/tmpmail-bin.pacscript
pacup -s packages/tmux/tmux.pacscript
pacup -s packages/topgrade-bin/topgrade-bin.pacscript
pacup -s packages/topgrade-musl-bin/topgrade-musl-bin.pacscript
pacup -s packages/torbrowser-launcher-git/torbrowser-launcher-git.pacscript
pacup -s packages/torguard-deb/torguard-deb.pacscript
pacup -s packages/tor/tor.pacscript
pacup -s packages/touchegg-deb/touchegg-deb.pacscript
pacup -s packages/touchegg-git/touchegg-git.pacscript
pacup -s packages/treefetch-bin/treefetch-bin.pacscript
pacup -s packages/tre-git/tre-git.pacscript
pacup -s packages/truckersmp-cli/truckersmp-cli.pacscript
pacup -s packages/ttf-fira-sans/ttf-fira-sans.pacscript
pacup -s packages/tuner-git/tuner-git.pacscript
pacup -s packages/tuner/tuner.pacscript
pacup -s packages/tutanota-app/tutanota-app.pacscript
pacup -s packages/u-boot-mobian-deb/u-boot-mobian-deb.pacscript
pacup -s packages/ulauncher-deb/ulauncher-deb.pacscript
pacup -s packages/universal-ctags-git/universal-ctags-git.pacscript
pacup -s packages/upscayl-app/upscayl-app.pacscript
pacup -s packages/uwufetch/uwufetch.pacscript
pacup -s packages/vega-strike-engine-git/vega-strike-engine-git.pacscript
pacup -s packages/vega-strike-git/vega-strike-git.pacscript
pacup -s packages/veracrypt-deb/veracrypt-deb.pacscript
pacup -s packages/viper4linux/viper4linux.pacscript
pacup -s packages/vivaldi-deb/vivaldi-deb.pacscript
pacup -s packages/vivarium/vivarium.pacscript
pacup -s packages/vscode-deb/vscode-deb.pacscript
pacup -s packages/vscodium-deb/vscodium-deb.pacscript
pacup -s packages/vyprvpn-deb/vyprvpn-deb.pacscript
pacup -s packages/waf/waf.pacscript
pacup -s packages/walc-app/walc-app.pacscript
pacup -s packages/warpinator-deb/warpinator-deb.pacscript
pacup -s packages/wazzapp-deb/wazzapp-deb.pacscript
pacup -s packages/webapp-manager-deb/webapp-manager-deb.pacscript
pacup -s packages/webapp-manager/webapp-manager.pacscript
pacup -s packages/webcord-deb/webcord-deb.pacscript
pacup -s packages/webtorrent-desktop-deb/webtorrent-desktop-deb.pacscript
pacup -s packages/weechat-git/weechat-git.pacscript
pacup -s packages/wezterm-app/wezterm-app.pacscript
pacup -s packages/wezterm-bin/wezterm-bin.pacscript
pacup -s packages/windscribe-beta-gui-deb/windscribe-beta-gui-deb.pacscript
pacup -s packages/wine-staging-git/wine-staging-git.pacscript
pacup -s packages/wsysmon-bin/wsysmon-bin.pacscript
pacup -s packages/xapps-common-deb/xapps-common-deb.pacscript
pacup -s packages/xfce4-deb/xfce4-deb.pacscript
pacup -s packages/xfce4-settings-pine-git/xfce4-settings-pine-git.pacscript
pacup -s packages/yabridge/yabridge.pacscript
pacup -s packages/yad/yad.pacscript
pacup -s packages/yafetch-git/yafetch-git.pacscript
pacup -s packages/yandex-browser-beta-deb/yandex-browser-beta-deb.pacscript
pacup -s packages/yandex-browser-stable-deb/yandex-browser-stable-deb.pacscript
pacup -s packages/yandex-disk-deb/yandex-disk-deb.pacscript
pacup -s packages/youtube-dl-git/youtube-dl-git.pacscript
pacup -s packages/youtube-music-deb/youtube-music-deb.pacscript
pacup -s packages/yt-dlp/yt-dlp.pacscript
pacup -s packages/zap/zap.pacscript
pacup -s packages/zentile-bin/zentile-bin.pacscript
pacup -s packages/zettlr-deb/zettlr-deb.pacscript
pacup -s packages/zoho-notebook-deb/zoho-notebook-deb.pacscript
pacup -s packages/zoom-deb/zoom-deb.pacscript
pacup -s packages/zotero/zotero.pacscript
